"""empty message

Revision ID: 0a552b8763d6
Revises: 327ebfd158b3
Create Date: 2026-02-12 17:00:13.323073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a552b8763d6'
down_revision: Union[str, Sequence[str], None] = '327ebfd158b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_type', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('is_finished', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'is_finished')
    op.drop_column('media', 'file_type')
    # ### end Alembic commands ###
