"""empty message

Revision ID: 0ff88ec4b828
Revises: e5a96f1fa7f2
Create Date: 2026-02-12 12:57:11.502395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff88ec4b828'
down_revision: Union[str, Sequence[str], None] = 'e5a96f1fa7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('model', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'model')
    # ### end Alembic commands ###
