"""empty message

Revision ID: 327ebfd158b3
Revises: 0ff88ec4b828
Create Date: 2026-02-12 16:36:13.205691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327ebfd158b3'
down_revision: Union[str, Sequence[str], None] = '0ff88ec4b828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vehicles', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    # ### end Alembic commands ###
